### ISSUE TITLE
你好，在你的训练集和验证集准确率的曲线中，跑出来的结果是验证集的准确率比训练集的还要高吗？然后验证集的loss是比训练集的要低的是吗？这和我之前的认知有点不一样，我以为训练集的准确率一般都会比验证集的要高。

### ISSUE THREAD

**Issue by laiguoji** [xiaochus/MobileNetV2#16]

**Comment by xiaochus** [comment]
@laiguoji 这里当时测试代码写反了，应该是高的。后来更新了代码但是没重新画图。

**Comment by laiguoji** [comment]
不好意思，我还有一个问题就是，如果是代码写反的话，为什么验证集的曲线比训练集的曲线还要平滑。------------------ 原始邮件 ------------------
发件人: "Larry"<notifications@github.com>
发送时间: 2019年5月21日(星期二) 晚上11:27
收件人: "xiaochus/MobileNetV2"<MobileNetV2@noreply.github.com>;
抄送: "laiguoji"<448690655@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [xiaochus/MobileNetV2] 你好，在你的训练集和验证集准确率的曲线中，跑出来的结果是验证集的准确率比训练集的还要高吗？然后验证集的loss是比训练集的要低的是吗？这和我之前的认知有点不一样，我以为训练集的准确率一般都会比验证集的要高。 (#16)



@laiguoji 这里当时测试代码写反了，应该是高的。后来更新了代码但是没重新画图。
 
&mdash;

**Comment by xiaochus** [comment]
@laiguoji 因为test和eval用的同样的数据处理函数，其中eval部分调用了train的部分导致了这个平滑现象，因为测试得是已经拟合的数据。
