### ISSUE TITLE
Alpha Parameter

### ISSUE THREAD

**Issue by ManeeshAyi** [xiaochus/MobileNetV2#17]
Hello Xiaochus,
It's a great work done by you in keras implementing Mobilenet V2. I didn't see any alpha parameter(width_multiplier) used in your code. How can change this hyperparameter in the code? I would greatly appreciate if someone could help me in setting this problem.
Thank You.

**Comment by ManeeshAyi** [comment]
@xiaochus Could you help me?

**Comment by xiaochus** [comment]
@ManeeshAyi What do you mean of width_multiplier? The depth_multiplier control the output of depth-wise part and the filters of 1*1 Conv2D control the number of output channel.

**Comment by ManeeshAyi** [comment]
@xiaochus Thanks for the reply. What I mean to say is that the alpha hyper parameter that is used to have thinner models (mentioned in MobileNet paper). Where the value of alpha is 0.35, 0.5, 0.75, 1 etc.

**Comment by xiaochus** [comment]
@ManeeshAyi OK, I know what you mean. I use alpha=1 in this model as default and i'll add a changeable parameter to control width.

**Comment by ManeeshAyi** [comment]
@xiaochus Thank you. Hope it is added soon

**Comment by ManeeshAyi** [comment]
@xiaochus Thank you for adding that.
